package estados;

/**
 *
 * @author juanmi
 */
public enum EstadosSkal {
    ESPERANDO_MENSAJE_INICIO, ESPERANDO_JARL_INICIO, ESPERANDO_SOLICITUD_TRADUCCION_BARCO, ESPERANDO_SOLICITUD_TRADUCCION_JARL, ESPERANDO_TRADUCCION_BARCO_2;
}
