package estados;

/**
 *
 * @author juanmi
 */
public enum EstadosBarco {
    INICIO_MISION, ESPERANDO_TRADUCCION_1, ESPERANDO_TOTEM_JARL, ESPERANDO_COORD_NAUFRAGOS, SOLICITAR_NUEVA_COORD_NAUF, SOLICITAR_COORD_JARL, ESPERANDO_TRADUCCION_2, ESPERANDO_COORD_JARL, 
    SOLICITAR_FIN_MISION, ESPERANDO_TRADUCCION_3, ESPERANDO_COORDENADAS_JARL ,ESPERANDO_HOHOHO;
}
