package estados;

/**
 *
 * @author juanmi
 */
public enum EstadosBarco {
    INICIO_MISION, ESPERANDO_TRADUCCION_INICIO, ESPERANDO_TOTEM_JARL, ESPERANDO_COORD_NAUFRAGOS, SOLICITAR_COORD_JARL, ESPERANDO_TRADUCCION_2, ESPERANDO_COORD_JARL, 
    SOLICITAR_FIN_MISION, ESPERANDO_TRACUCCION_FINAL, ESPERANDO_FINAL;
}
